require "options"
require "keymaps"

require "plugins"
require "plugins/autopair"
require "plugins/comment"
require "plugins/cmp"
require "plugins/dashboard"
require "plugins/gitsigns"
require "plugins/illuminate"
require "plugins/lsp"
require "plugins/lualine"
require "plugins/luasnip"
require "plugins/matchup"
require "plugins/neogit"
require "plugins/neoscroll"
require "plugins/nvimtree"
require "plugins/spectre"
require "plugins/telescope"
require "plugins/treesitter"
require "plugins/treesitter-textobjects"
require "plugins/trouble"
require "plugins/better-whitespace"

require "plugins/tokyonight"
require "plugins/bufferline"

require "highlight"
