require "options"
require "keymaps"

require "plugins"
require "plugins/autopair-config"
require "plugins/comment-config"
require "plugins/cmp-config"
require "plugins/dashboard-config"
require "plugins/gitsigns-config"
require "plugins/illuminate-config"
require "plugins/lsp-config"
require "plugins/lualine-config"
require "plugins/luasnip-config"
require "plugins/matchup-config"
require "plugins/neogit-config"
require "plugins/neoscroll-config"
require "plugins/nvimtree-config"
require "plugins/spectre-config"
require "plugins/telescope-config"
require "plugins/treesitter-config"
require "plugins/treesitter-textobjects-config"
require "plugins/trouble-config"
require "plugins/vim-better-whitespace-config"

require "plugins/tokyonight-config"
require "plugins/bufferline-config"

require "highlight"
